name: VirTaxonomer
channels:
  - pytorch
  - nvidia
  - bioconda
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - aiohappyeyeballs=2.4.4
  - aiohttp=3.11.11
  - aiosignal=1.3.2
  - anytree=2.12.1
  - async-timeout=5.0.1
  - attrs=24.3.0
  - aws-c-auth=0.8.0
  - aws-c-cal=0.8.1
  - aws-c-common=0.10.6
  - aws-c-compression=0.3.0
  - aws-c-event-stream=0.5.0
  - aws-c-http=0.9.2
  - aws-c-io=0.15.3
  - aws-c-mqtt=0.11.0
  - aws-c-s3=0.7.7
  - aws-c-sdkutils=0.2.2
  - aws-checksums=0.2.2
  - aws-crt-cpp=0.29.8
  - aws-sdk-cpp=1.11.458
  - azure-core-cpp=1.14.0
  - azure-identity-cpp=1.10.0
  - azure-storage-blobs-cpp=12.13.0
  - azure-storage-common-cpp=12.8.0
  - azure-storage-files-datalake-cpp=12.12.0
  - biopython=1.84
  - blas=2.16
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.4
  - ca-certificates=2024.12.14
  - certifi=2024.12.14
  - cffi=1.17.1
  - charset-normalizer=3.4.1
  - colorama=0.4.6
  - cpython=3.10.16
  - cuda-cudart=12.4.127
  - cuda-cupti=12.4.127
  - cuda-libraries=12.4.1
  - cuda-nvrtc=12.4.127
  - cuda-nvtx=12.4.127
  - cuda-opencl=12.6.77
  - cuda-runtime=12.4.1
  - cuda-version=12.6
  - datasets=3.2.0
  - dill=0.3.8
  - filelock=3.16.1
  - frozenlist=1.5.0
  - fsspec=2024.9.0
  - gflags=2.2.2
  - glog=0.7.1
  - gmp=6.3.0
  - gmpy2=2.1.5
  - h2=4.1.0
  - hpack=4.0.0
  - huggingface_hub=0.27.1
  - hyperframe=6.0.1
  - idna=3.10
  - intel-openmp=2022.0.1
  - jinja2=3.1.5
  - keyutils=1.6.1
  - krb5=1.21.3
  - ld_impl_linux-64=2.43
  - libabseil=20240722.0
  - libarrow=18.1.0
  - libarrow-acero=18.1.0
  - libarrow-dataset=18.1.0
  - libarrow-substrait=18.1.0
  - libblas=3.8.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.8.0
  - libcrc32c=1.1.2
  - libcublas=12.4.5.8
  - libcufft=11.2.1.3
  - libcufile=1.11.1.6
  - libcurand=10.3.7.77
  - libcurl=8.11.1
  - libcusolver=11.6.1.9
  - libcusparse=12.3.1.170
  - libedit=3.1.20240808
  - libev=4.33
  - libevent=2.1.12
  - libffi=3.4.2
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libgomp=14.2.0
  - libgoogle-cloud=2.33.0
  - libgoogle-cloud-storage=2.33.0
  - libgrpc=1.67.1
  - libiconv=1.17
  - liblapack=3.8.0
  - liblapacke=3.8.0
  - liblzma=5.6.3
  - libnghttp2=1.64.0
  - libnpp=12.2.5.30
  - libnsl=2.0.1
  - libnvfatbin=12.6.77
  - libnvjitlink=12.4.127
  - libnvjpeg=12.3.1.117
  - libparquet=18.1.0
  - libprotobuf=5.28.3
  - libre2-11=2024.07.02
  - libsqlite=3.47.2
  - libssh2=1.11.1
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libthrift=0.21.0
  - libutf8proc=2.9.0
  - libuuid=2.38.1
  - libxcrypt=4.4.36
  - libxml2=2.13.5
  - libzlib=1.3.1
  - llvm-openmp=15.0.7
  - lz4-c=1.10.0
  - markupsafe=3.0.2
  - mkl=2020.2
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - multidict=6.1.0
  - multiprocess=0.70.16
  - ncurses=6.5
  - networkx=3.4
  - numpy=1.22.4
  - openssl=3.4.0
  - orc=2.0.3
  - packaging=24.2
  - pandas=2.2.3
  - pip=24.3.1
  - propcache=0.2.1
  - pyarrow=18.1.0
  - pyarrow-core=18.1.0
  - pycparser=2.22
  - pysocks=1.7.1
  - python=3.10.16
  - python-dateutil=2.9.0.post0
  - python-tzdata=2024.2
  - python-xxhash=3.5.0
  - python_abi=3.10
  - pytorch=2.5.1
  - pytorch-cuda=12.4
  - pytorch-mutex=1.0
  - pytz=2024.1
  - pyyaml=6.0.2
  - re2=2024.07.02
  - readline=8.2
  - regex=2024.11.6
  - requests=2.32.3
  - s2n=1.5.10
  - safetensors=0.5.2
  - setuptools=75.8.0
  - six=1.17.0
  - snappy=1.2.1
  - sortedcontainers=2.4.0
  - sympy=1.13.3
  - tk=8.6.13
  - tokenizers=0.21.0
  - torchtriton=3.1.0
  - tqdm=4.67.1
  - transformers=4.48.0
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2024b
  - urllib3=2.3.0
  - wheel=0.45.1
  - xxhash=0.8.2
  - yaml=0.2.5
  - yarl=1.18.3
  - zstandard=0.23.0
  - zstd=1.5.6
